# Mybatis 的相关配置
mybatis:
  # 扫描配置文件
  mapper-locations: classpath:mapper/*.xml
  # 别名的配置
  type-aliases-package: com.zwd.project.pojo

spring: 
    # 数据源配置
  datasource: 
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # Thymeleaf配置
  thymeleaf: 
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8


